"""Render a static preview of the Streamlit demo for the README and portfolio.

The figure mirrors the layout of ``src/app_streamlit.py``:

    - top:    three normalised sensor traces along one engine's life
    - bottom: per-window reconstruction error with the threshold drawn
              and the anomalous windows highlighted

It is regenerated by:

    python -m scripts.demo_preview
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent


def _style_palette():
    return {
        "BG_PANEL": "#0d1220", "BG_AXES": "#0c101c",
        "FG_0": "#e7ecf5",     "FG_1": "#9aa3b8",
        "PURPLE": "#7c5cff",   "CYAN": "#22d3ee",
        "PINK": "#f472b6",     "AMBER": "#fbbf24",
    }


def main(unit: int = 95, out_path: str | Path = "figures/demo.png") -> None:
    import json
    import matplotlib.pyplot as plt

    from src.data import build_dataset, load_split, INFORMATIVE_SENSORS_FD001
    from src.train import load_checkpoint, reconstruction_errors

    pal = _style_palette()
    plt.rcParams.update({
        "figure.facecolor": pal["BG_PANEL"],
        "savefig.facecolor": pal["BG_PANEL"],
        "axes.facecolor": pal["BG_AXES"],
        "axes.edgecolor": (1, 1, 1, 0.20),
        "axes.labelcolor": pal["FG_0"],
        "axes.titlecolor": pal["FG_0"],
        "axes.labelsize": 11.5, "axes.titlesize": 12, "axes.titleweight": "bold",
        "axes.grid": True, "grid.color": (1, 1, 1, 0.05), "grid.linewidth": 0.7,
        "xtick.color": pal["FG_1"], "ytick.color": pal["FG_1"],
        "text.color": pal["FG_0"],
        "legend.facecolor": pal["BG_PANEL"],
        "legend.edgecolor": (1, 1, 1, 0.20),
        "legend.labelcolor": pal["FG_0"],
        "savefig.dpi": 170, "savefig.bbox": "tight",
    })

    ds = build_dataset(raw_dir=str(ROOT / "data" / "raw"))
    model, payload = load_checkpoint(str(ROOT / "checkpoints" / "autoencoder.pt"))
    with open(ROOT / "data" / "eval_report.json") as fh:
        threshold = float(json.load(fh)["threshold"])

    raw = load_split("FD001", "train", raw_dir=str(ROOT / "data" / "raw"))
    sensor_cols = [f"sensor_{i}" for i in INFORMATIVE_SENSORS_FD001]
    sub = raw[raw["unit"] == unit].sort_values("cycle").reset_index(drop=True)
    arr = sub[sensor_cols].to_numpy(dtype=np.float32)
    arr_norm = (arr - ds.mean) / ds.std

    seq_len = ds.seq_len
    starts = np.arange(0, arr_norm.shape[0] - seq_len + 1)
    xs = np.stack([arr_norm[s : s + seq_len] for s in starts], axis=0)
    err = reconstruction_errors(model, xs)
    end_idx = starts + seq_len - 1
    flagged = err > threshold

    chosen_sensors = sensor_cols[:3]
    palette = [pal["PURPLE"], pal["CYAN"], pal["PINK"]]

    fig, (ax_top, ax_bot) = plt.subplots(
        2, 1, figsize=(10.0, 5.6), sharex=True,
        gridspec_kw={"height_ratios": [3, 2]},
    )

    for col, color in zip(chosen_sensors, palette):
        ax_top.plot(sub["cycle"], sub[col], color=color, lw=1.3,
                    alpha=0.95, label=col)
    # Highlight flagged windows on the upper panel.
    for c in sub["cycle"].iloc[end_idx[flagged]]:
        ax_top.axvspan(c - 0.5, c + 0.5, color=pal["AMBER"], alpha=0.06,
                       linewidth=0)
    ax_top.set_ylabel("raw sensor reading")
    ax_top.set_title(
        f"Streamlit demo preview - engine #{unit} - flagged regions in amber")
    ax_top.legend(ncol=len(chosen_sensors), loc="upper center",
                  bbox_to_anchor=(0.5, -0.02), fontsize=9)

    ax_bot.plot(sub["cycle"].iloc[end_idx], err, color=pal["PURPLE"], lw=1.4,
                label="reconstruction MSE")
    ax_bot.axhline(threshold, color=pal["PINK"], lw=1.3, ls="--",
                   label=f"threshold = {threshold:.3f}")
    ax_bot.fill_between(
        sub["cycle"].iloc[end_idx], err, threshold,
        where=flagged, color=pal["AMBER"], alpha=0.45, linewidth=0,
        label=f"flagged ({int(flagged.sum())} / {len(err)} windows)",
    )
    ax_bot.set_xlabel("operational cycle")
    ax_bot.set_ylabel("anomaly score")
    ax_bot.legend(loc="upper left", fontsize=9)

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(out)
    plt.close(fig)
    print(f"[ok] {out}")


if __name__ == "__main__":
    import argparse

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--unit", type=int, default=95)
    p.add_argument("--out", default="figures/demo.png")
    args = p.parse_args()
    main(unit=args.unit, out_path=args.out)
